Shwack of NVN updates
blackbirdinteractive/bgfx pull request #29
Opened 2021-09-01 07:20 UTC by bbi-timstump

- support toggling vsync (requires enabling it in Target Manager)
- change swapchain to always create at 1080p
  - not sure if we should still recreate depth, anything sampling it will need to be aware that it's always 1080p
- use nvnWindowSetCrop to crop swapchain in 720p mode (no resizing swapchain required)
- track highwater of command list command/control buffers
- remove unused files that also cleans up C++17 warning
- change to better invalid values for first init
- fix registering images (was stomping texture registration)
- support MSAA backbuffer
- support MSAA textures (sampling still seems questionable)
- fix shader program stages mask (read from shaders)
- fix assao example shaders (treat GLSL and NVN path the same)
- remove unused vertex inputs from bloom sample
- occlusion query support
- fix vertex attribute binding to always preserve the binding order coming from the shader
  - this includes instance attributes
- vertex attributes are potentially a sparse list, so always configure all bindings
- in lieu of debug names for shaders, set a name on the shader structure for debugging
- aligning a bunch of variable names to bgfx coding style
- fix some configuration issues if BGFX_CONFIG_RENDERER_NVN isn't defined
- unfix bloom vertex attributes, they're a good test to ensure attribute binding is working
- rename nbody particle shaders to not collide with builtin particle shaders

2021-09-02 20:03 UTC, bbi-davidgalloway requested changes

2021-09-02 20:59 UTC, bbi-timstump commented on src/renderer_nvn/resources.cpp
> +			}
GLSLC calls them locations, too.  bgfx refers to them as reg indexes.

2021-09-09 02:37 UTC, bbi-michaelanderson commented on examples/24-nbody/nbody.cpp
> +			m_particleProgram = loadProgram("vs_nbody_particle", "fs_nbody_particle");
Thanks! This cost  me a couple hours.

2021-09-09 07:19 UTC, bbi-davidgalloway commented on examples/46-shaderbuffer/shaderbuffer.cpp
> +/*
I tested this on DX11 and it worked. It was odd that the examples.cmake needed to be extended to include examples 40 through 46. Apparently it needs to be updated.

2021-09-09 07:23 UTC, bbi-davidgalloway commented on src/renderer_nvn.cpp
> +			//m_resources.m_shaderBuffers[_handle.idx].update(0, _mem->size, _mem->data);
How are you ensuring your buffer updates are coherent?
Also why did you end up implementing it here instead of in m_shaderBuffer[n].update()
Do you still need the commented out part?

2021-09-09 07:25 UTC, bbi-davidgalloway approved these changes

2021-09-09 21:16 UTC, bbi-timstump commented on examples/24-nbody/nbody.cpp
> +			m_particleProgram = loadProgram("vs_nbody_particle", "fs_nbody_particle");
That really was incredibly annoying, haha.  I hadn't really looked into why this and the particles examples would randomly stop working until you mentioned that there was a name collision.

2021-09-09 21:19 UTC, bbi-timstump commented on src/renderer_nvn.cpp
> +			//m_resources.m_shaderBuffers[_handle.idx].update(0, _mem->size, _mem->data);
NVN provides a guarantee that data is coherent after a copy so we don't need any extra barriers.  Copies always happen at the start of the frame so the data will be valid on the frame that uses the buffer after the copy.

2021-09-09 21:22 UTC, bbi-timstump commented on src/renderer_nvn.cpp
> +			//m_resources.m_shaderBuffers[_handle.idx].update(0, _mem->size, _mem->data);
BufferNVN::update is the CPU version of the copy, this uses a staging resource to do the copy since the GPU may already be using the buffer.  Usage patterns are a little different for these buffers vs vertex/index buffers in that vertex/index buffers are very rarely updated dynamically while shader buffers would almost exclusively be updated dynamically.

2021-09-09 21:27 UTC, bbi-davidgalloway commented on src/renderer_d3d11.cpp
> +
It seems these ShaderBuffer changes should be brought over to Badger?

2021-09-09 22:31 UTC, bbi-timstump commented on src/renderer_d3d11.cpp
> +
It is in Badger, it's where I copy/pasted from :)

2021-09-09 22:42 UTC, merged